import type { Language } from "@/lib/i18n";

const zh = {
  adminTitle: "管理后台",
  workspace: "内容工作台",
  navigation: "管理菜单",
  dashboard: "仪表盘",
  categories: "分类管理",
  sites: "网站管理",
  visitSite: "访问前台",
  save: "保存数据",
  saving: "正在保存…",
  loading: "正在读取目录数据",
  loadFailed: "读取数据失败",
  retry: "重新加载",
  unsaved: "有尚未保存的修改",
  saved: "所有修改均已保存",
  token: "ADMIN_TOKEN 管理令牌",
  tokenHint: "仅在服务端配置令牌时需要填写",
  hideToken: "隐藏令牌",
  showToken: "显示令牌",
  totalCategories: "分类数量",
  totalSites: "网站数量",
  totalSections: "分组数量",
  translatedSites: "含扩展翻译",
  dashboardIntro: "快速查看目录结构和编辑状态。所有修改会先保留在当前页面，点击保存后写入数据库。",
  recentCategories: "分类概览",
  recentCategoriesHelp: "按当前目录顺序展示分类及收录数量",
  quickActions: "快捷操作",
  manageCategories: "管理分类",
  manageSites: "管理网站",
  categoryList: "分类列表",
  categoryListHelp: "维护分类名称、图标、结构和显示顺序",
  addCategory: "新增分类",
  editCategory: "编辑分类",
  deleteCategory: "删除分类",
  deleteCategoryTitle: "确认删除分类？",
  deleteCategoryDescription: "分类内的网站和分组也会从当前草稿中删除。保存数据后此操作才会写入数据库。",
  categoryZh: "中文分类名称",
  categoryEn: "英文分类名称",
  categoryIcon: "分类图标",
  categoryMode: "内容结构",
  standardLinks: "普通链接",
  groupedLinks: "分组链接",
  friendLinks: "友情链接",
  order: "顺序",
  iconAndName: "图标与名称",
  englishName: "英文名称",
  structure: "结构",
  count: "网站数",
  actions: "操作",
  moveUp: "上移",
  moveDown: "下移",
  cancel: "取消",
  confirm: "确认",
  update: "更新",
  create: "创建",
  siteList: "网站列表",
  siteListHelp: "搜索、筛选并维护目录中的全部网站",
  addSite: "新增网站",
  editSite: "编辑网站",
  deleteSite: "删除网站",
  deleteSiteTitle: "确认删除网站？",
  deleteSiteDescription: "网站会从当前草稿中移除，保存数据后才会写入数据库。",
  searchSites: "搜索名称、简介、网址或分类…",
  allCategories: "全部分类",
  site: "网站",
  category: "分类",
  section: "分组",
  noSection: "无分组",
  url: "网站 URL",
  logo: "Logo 路径",
  qrcode: "二维码路径",
  titleZh: "中文名称",
  titleEn: "英文名称",
  descriptionZh: "中文简介",
  descriptionEn: "英文简介",
  extraTranslations: "其他语言翻译",
  extraTranslationsHelp: "保留并编辑中文、英文之外的已有翻译",
  addLanguage: "添加语言",
  languageCode: "语言代码",
  translatedTitle: "翻译名称",
  translatedDescription: "翻译简介",
  invalidLanguage: "请输入 de、ja 或 pt-BR 等有效语言代码",
  emptyCategories: "还没有分类，请先新增分类。",
  emptySites: "没有符合条件的网站。",
  previous: "上一页",
  next: "下一页",
  page: "页",
  rows: "条",
  closeMenu: "关闭菜单",
  openMenu: "打开菜单"
} as const;

const en: Record<keyof typeof zh, string> = {
  adminTitle: "Admin",
  workspace: "Content workspace",
  navigation: "Management",
  dashboard: "Dashboard",
  categories: "Categories",
  sites: "Websites",
  visitSite: "Visit website",
  save: "Save data",
  saving: "Saving…",
  loading: "Loading directory data",
  loadFailed: "Unable to load data",
  retry: "Try again",
  unsaved: "You have unsaved changes",
  saved: "All changes are saved",
  token: "ADMIN_TOKEN",
  tokenHint: "Required only when a server-side token is configured",
  hideToken: "Hide token",
  showToken: "Show token",
  totalCategories: "Categories",
  totalSites: "Websites",
  totalSections: "Groups",
  translatedSites: "Extra translations",
  dashboardIntro: "Review the directory and edit status. Changes stay in this page until you save them to the database.",
  recentCategories: "Category overview",
  recentCategoriesHelp: "Categories and entry counts in their current order",
  quickActions: "Quick actions",
  manageCategories: "Manage categories",
  manageSites: "Manage websites",
  categoryList: "Category list",
  categoryListHelp: "Maintain names, icons, structures, and display order",
  addCategory: "Add category",
  editCategory: "Edit category",
  deleteCategory: "Delete category",
  deleteCategoryTitle: "Delete this category?",
  deleteCategoryDescription: "Its websites and groups will be removed from the draft. The database changes only after you save.",
  categoryZh: "Chinese category name",
  categoryEn: "English category name",
  categoryIcon: "Category icon",
  categoryMode: "Content structure",
  standardLinks: "Standard links",
  groupedLinks: "Grouped links",
  friendLinks: "Friend links",
  order: "Order",
  iconAndName: "Icon and name",
  englishName: "English name",
  structure: "Structure",
  count: "Websites",
  actions: "Actions",
  moveUp: "Move up",
  moveDown: "Move down",
  cancel: "Cancel",
  confirm: "Confirm",
  update: "Update",
  create: "Create",
  siteList: "Website list",
  siteListHelp: "Search, filter, and maintain every website in the directory",
  addSite: "Add website",
  editSite: "Edit website",
  deleteSite: "Delete website",
  deleteSiteTitle: "Delete this website?",
  deleteSiteDescription: "It will be removed from the draft. The database changes only after you save.",
  searchSites: "Search names, descriptions, URLs, or categories…",
  allCategories: "All categories",
  site: "Website",
  category: "Category",
  section: "Group",
  noSection: "No group",
  url: "Website URL",
  logo: "Logo path",
  qrcode: "QR code path",
  titleZh: "Chinese name",
  titleEn: "English name",
  descriptionZh: "Chinese description",
  descriptionEn: "English description",
  extraTranslations: "Additional translations",
  extraTranslationsHelp: "Preserve and edit translations beyond Chinese and English",
  addLanguage: "Add language",
  languageCode: "Language code",
  translatedTitle: "Translated name",
  translatedDescription: "Translated description",
  invalidLanguage: "Enter a valid language code such as de, ja, or pt-BR",
  emptyCategories: "No categories yet. Create one first.",
  emptySites: "No websites match these filters.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  rows: "rows",
  closeMenu: "Close menu",
  openMenu: "Open menu"
};

export type AdminCopy = Record<keyof typeof zh, string>;

export function getAdminCopy(language: Language): AdminCopy {
  return language === "zh" ? zh : en;
}
